from app.api.auth import router as auth_router
from app.api.categories import router as categories_router
from app.api.products import router as products_router
from app.api.cart import router as cart_router
from app.api.checkout import router as checkout_router
from app.api.profile import router as profile_router
from app.api.favorites import router as favorites_router
from app.api.admin.stats import router as admin_stats_router
from app.api.admin.products import router as admin_products_router
from app.api.admin.categories import router as admin_categories_router
from app.api.admin.orders import router as admin_orders_router
from app.api.admin.users import router as admin_users_router
from app.api.admin.uploads import router as admin_uploads_router
